{% set version = "1.22.5" %}
{% set name = "PyMuPDF" %}
{% set sha256 = "5ec8d5106752297529d0d68d46cfc4ce99914aabd99be843f1599a1842d63fe9" %}

package:
  name: pymupdf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-build-isolation .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - fitz
  source_files:
    - tests/
  commands:
    - pip check
    - cd tests
    - pytest -v .
  requires:
    - pip
    - pytest
    - fonttools

about:
  home: https://github.com/pymupdf/PyMuPDF
  license: COPYING
  license_family: AGPL
  summary: PyMuPDF is an enhanced Python binding for MuPDF.
  description: |
    PyMuPDF adds Python bindings and abstractions to MuPDF, a lightweight PDF, XPS,
    and eBook viewer, renderer, and toolkit. Both PyMuPDF and MuPDF are maintained
    and developed by Artifex Software, Inc.
    MuPDF can access files in PDF, XPS, OpenXPS, CBZ, EPUB and FB2 (eBooks) formats,
    and it is known for its top performance and exceptional rendering quality.
    In addition, about 10 popular image formats can also be handle including .png, 
    .jpg, .bmp, .tiff, etc.
  dev_url: https://github.com/pymupdf/PyMuPDF
  doc_url: https://pymupdf.readthedocs.io/en/latest/
